# Generated by Django 4.1.4 on 2022-12-31 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
